### ISSUE TITLE
[Bug]: 从 RS 到 R-secure 插件转化过程，出现密码不匹配

### ISSUE THREAD

**Issue by YIRU69** [sboesen/remotely-secure#4] opened 2023-11-07 06:25 UTC
### What happened?

```
remotely-secure-1699338212659：中断同步，同步来源=manual，出错阶段=checking_password

Error: password_not_matched
    at U_.syncRun (plugin:remotely-secure:185:1811)

```
没有额外的更改其他的配置，直接复制data.json 文件进行覆盖

### What OS are you using?

Windows

### What remote cloud services are you using?

S3

### Version of the plugin

4.1

### Version of Obsidian

1.4.16

### Using password or not

- [X] Yes.

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by Devinaille** [comment] 2023-11-10 02:25
get the same error on COS without local password

**Comment by sboesen** [comment] 2023-11-11 08:51
Hello, thank you for the bug submission. Could you please confirm if the remote storage location was previously used and contains files encrypted with an older version of this plugin (remotely-save)? The encryption configuration used in remotely-secure is not backwards compatible.

**Comment by YIRU69** [comment] 2023-11-12 01:42
> Hello, thank you for the bug submission. Could you please confirm if the remote storage location was previously used and contains files encrypted with an older version of this plugin (remotely-save)? The encryption configuration used in remotely-secure is not backwards compatible.

Yes, it is. The older version of the plugin have encrypted files. So what can I do? I want to use you plugin and not need to rebuild a new.

**Comment by sboesen** [comment] 2023-11-12 08:39
I intentionally didn't include the older encryption code as it had security weaknesses and I wanted to improve on the complexity/readability of the security-sensitive code. The easiest way to migrate from remotely-save (or other forks) to remotely secure is:

1. Make a local, unencrypted backup of your files (make sure to synchronize all changes across your devices)
2. Disable the remotely-save plugin
3. Enable remotely-secure and set a new encryption password
4. Delete the encrypted files in your cloud provider (or make a new S3 bucket in this case)
5. Perform a sync using remotely-secure

**Comment by YIRU69** [comment] 2023-11-12 11:03
@sboesen  Hi Another bug shown
```
AggregateError: 
    Error: 700-Extras/701-attachments/Most Common English Writing Habits Of Chinese-excalidraw.png: Failed to fetch
        at eval (plugin:remotely-secure:114:50370)
    Error: 700-Extras/701-attachments/These unilateral developments differ in their specifics.mp3: Failed to fetch
        at eval (plugin:remotely-secure:114:50370)
    Error: 700-Extras/701-attachments/But that doesn't mean crucial ethical issues involving.mp3: Failed to fetch
        at eval (plugin:remotely-secure:114:50370)
    Error: too many errors, stop the remaining tasks
        at zme (plugin:remotely-secure:114:50473)
        at async U_.syncRun (plugin:remotely-secure:185:2794)
    at zme (plugin:remotely-secure:114:50529)
    at async U_.syncRun (plugin:remotely-secure:185:2794)
```

**Comment by YIRU69** [comment] 2023-11-12 11:04
It too many error from my files. I use the rs show right but the R-secure show too many error. Why?

**Comment by sboesen** [comment] 2023-11-12 22:37
Hmm, I am not able to reproduce this issue locally. Is it possible to temporarily disable the other plugins to isolate the error? Are you using AWS S3 for syncing or if not which provider?

If you create a new vault and a new S3 bucket and sync does this still occur?

**Comment by YIRU69** [comment] 2023-11-13 00:42
I build a new S3 bucket on `cloud.tencent`. 

And I test a new vault and a new S3 bucket. Sync still error too many. 

I give you my test vault.
[1.zip](https://github.com/sboesen/remotely-secure/files/13329642/1.zip)

**Comment by sboesen** [comment] 2023-11-13 06:26
Thank you - I tried your test vault and I was able to get it to sync  between two local vaults using S3 via https://storj.io, I don't have an account on cloud.tencent but it should be the same if they use an S3 API. I did have to disable some of the CSS files for it to display the sync button & also added the Remotely Secure plugin.

<img width="1007" alt="Screenshot 2023-11-12 at 10 25 09 PM" src="https://github.com/sboesen/remotely-secure/assets/248703/cdc730d3-24fe-4266-832f-d09776108bcd">

Please let me know if there is something I missed, definitely want to get this working for you!

**Comment by sboesen** [comment] 2023-11-13 06:34
There is also a new update for Remotely Secure, 0.4.3 - please check for updates and update to it, it should result in less errors in the console (accidentally included a log statement we didn't need). May help narrow down the errors you're getting here!

**Comment by YIRU69** [comment] 2023-11-13 13:45
Hi, sync notes works on 0.4.5. But when I sync all my files and then to sync again. It show error password.
It is too sad😥
```
plugin:remotely-secure:185 remotely-secure-1699882945538：中断同步，同步来源=manual，出错阶段=checking_password
```

**Comment by YIRU69** [comment] 2023-11-13 13:54
The same issue  #5

**Comment by sboesen** [comment] 2023-11-13 19:45
I have fixed the `invalid_text_after_decryption` error in 0.4.6, please tell me if you continue experiencing an error after updating. Removed the check entirely that can produce that error. Thanks!

**Comment by sboesen** [comment] 2023-11-14 02:02
Closing this issue as I believe the sync issues have been resolved in the latest version. Please let me know if that's not the case and feel free to re-open with more details! Thanks.

**Closed by sboesen** 2023-11-14 02:02 UTC
Labels: bug
