### ISSUE TITLE
[Feature Request]: Fix Webdav / Support HTTP for self-hosted owncloud

### ISSUE THREAD

**Issue by DerNiccoo** [sboesen/remotely-secure#16] opened 2023-11-15 21:16 UTC
### What feature are you suggesting?

Hi, I tried it with the remotely save and now with remotely secure. First: thank you for updating the plugin!

Since data protection is kinda important for me, I prefer to host my own cloud (nextcloud / owncloud) only available within my local network. Because of this, and other stuff I've running on my server, I'm hosting owncloud on port 7980. Within the browser, I can simply access my cloud and everything works. But when I try to enter the domain name `http://cloud.fritz.box:7980` with my credentials, I get a 405. If I try it with the IP e.g. `http://192.168.178.40:7980` and the credentials, I get a 400.

### What remote cloud services are you using, or suggesting adding the feature to?

webdav

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by sboesen** [comment] 2023-11-15 23:01
Glad to help & see people getting value from the updated plugin!

Just to clarify: it looks like you're saying the webdav implementation is not working for you (it's the only one that is untested, so this is good feedback). Did I misunderstand?

If so I can convert this issue into a bug report & hopefully find some time to get it working. Pull requests also greatly appreciated.

**Comment by DerNiccoo** [comment] 2023-11-16 16:17
I'm not sure if this is a bug or missing feature. I guess both plugins uses the underlying HTTP Client from Obsidian. Might be a protection thing. First I tried it with a self-hosted, local instance of nextcloud. No Cert, only available in our LAN. I always got the error that I have an invalid Cert (which make sense, since I had none, but proxy was configured to work without cert).

I switched to owncloud, so I could easier host on other ports than 443. Now I don't need a proxy and owncloud is running in our LAN. Now I get the above mentioned errors. Would be great if there was an option to disable Cert check or what ever the main cause of the 405/400 is.

**Comment by sboesen** [comment] 2023-11-16 20:33
I'll mark it as a bug unless we have other confirmations when I'm able to check this. Will see if I can get a test environment set up easily

**Comment by sboesen** [comment] 2023-11-16 22:52
Hmm, I am getting an error `net::ERR_EMPTY_RESPONSE` no matter what I do. Have you seen this?

I can't tell if our usage of the webdav client isn't ideal or if the client itself could use improvement. This may take some time to fix, and may possibly require rewriting webdav usage within remotely-secure in the worst case.

Did this work previously in remotely-save?

**Comment by DerNiccoo** [comment] 2023-11-18 08:00
No, it didn't work for me before. I found like 2-3 similar requests on the remotely-save issues page. And I found some requests on reddit about it. 

And I did not see the error before? I only had the described ones above.

**Comment by sboesen** [comment] 2023-11-18 18:57
Thanks for confirming. Definitely worried this may require a rewrite of the webdav implementation.

**Comment by sboesen** [comment] 2023-11-22 20:12
> I sync via NextCloud WebDav.

@caunus are you able to confirm the webdav implementation works out of the box for you? Any issues with syncing apart from the relatively slow sync speed (#31)?

**Comment by caunus** [comment] 2023-11-23 07:47
@sboesen Yes works more and less out of the box. because I was using remotely-save before, I synced all my device to have a master on my Mac, after that I delete the sync-folder on my NextCloud and all local vaults on the other devices. Delete the old plugin and then using remotely-secure with all the old credentials. First sync on the Mac also needs with my 16k DSL some time, but the status works great. Nevertheless a few issues. During the upload I had dev tools open and sometimes the sync (at least one connection of the default ) stop with an error while trying to transfer some files. But at the end all the files were transferred. Only one file not sitting inside the .obsidan, funny enough the option to sync the folder was off. When switching the option on this was transferred as well. I have no encryption on. Sync with my linux machine work after that fine.  Better as with the old plugin becaue all the plugins was transferred as well and was in the same state (on/off) as on the Mac. 
I had one issue with NextCloud, when trying to delete the old sync-vault. There was several file locked in the folder, so I was unable to rename or delete the folder. This one helps: https://help.nextcloud.com/t/file-is-locked-how-to-unlock/1883. I now switch the locking feature on my nextcloud off. Hope this helps.

**Comment by sboesen** [comment] 2023-11-23 17:52
Thank you! Thank helps a ton. Will give nextcloud a try as a test environment to figure out why we are experiencing errors with syncing with own cloud.

Really appreciate the detailed reply, thanks!

**Comment by DerNiccoo** [comment] 2023-11-23 19:46
@caunus is your NextCloud also self hosted and without a public domain? I.e. not reachable besides your local network?

**Comment by caunus** [comment] 2023-11-23 20:40
@DerNiccoo  I hostet it outside of my local network.

**Comment by caunus** [comment] 2023-11-24 07:39
> @DerNiccoo I hostet it outside of my local network.

I didn‘t  saw the context of you question before. My Nextcloud  is selfhosted on the server of my provider with https.

**Comment by sboesen** [comment] 2023-11-24 08:40
I'm confused how this would be an issue for a locally setup server with no certs unless (just guessing) the plugin doesn't support plain HTTP traffic, which I suppose is possible but it doesn't feel like there's any sign of that.

**Comment by sboesen** [comment] 2023-11-24 08:54
Hmm, I actually just got it to work using a [local webdav server ](https://github.com/micromata/dave) for testing. Synced twice, looks like I had a minor misconfiguration. @DerNiccoo not sure why you would be getting a 400/405, have you tested that setup with a different webdav client and it works?

**Comment by sboesen** [comment] 2023-11-24 09:12
That would be very helpful, thank you! Please let me know if you can reproduce the issue. Might be locally-hosted nextcloud specific.

**Comment by caunus** [comment] 2023-11-24 09:19
Just check my setting for Joplin sync and obsidian. There is a different with the / at the end of the URL. Obsidian https://myserver.com/remote.php/dav/files/caunus/ and for Joplin without slash. I can remember that I had trouble with that. https://myserver.com/remote.php/dav/files/caunus/Joplin

**Comment by sboesen** [comment] 2023-11-25 16:50
Yes - thanks for confirming it worked for you! I'll go ahead and close the issue. Do open a new issue if you experience other issues with webdav.

**Closed by sboesen** 2023-11-25 16:50 UTC
Labels: bug

**Comment by caunus** [comment] 2023-12-01 16:05
@sboesen did you still need my support with setting up some new installations on internal NextCloud instances? If yes what jkind of protocol I short switch on?
