### ISSUE TITLE
[Bug]: 不使用加密密码无法增量同步

### ISSUE THREAD

**Issue by Devinaille** [sboesen/remotely-secure#5] opened 2023-11-10 02:58 UTC
### What happened?

使用S3模式通不到腾讯云COS，在不填【基本设置】【密码】的情况下，能进行第一词的全量同步，但不能进行第二次手动同步，提示
"中断同步，同步来源=manual，出错阶段=checking_password"

### What OS are you using?

Windows

### What remote cloud services are you using?

others

### Version of the plugin

0.4.1

### Version of Obsidian

v1.4.16

### Using password or not

- [ ] Yes.

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by sboesen** [comment] 2023-11-11 08:56
Hi, thanks for the bug submission. Could you please confirm whether or not the issue I described [here](https://github.com/sboesen/remotely-secure/issues/4#issuecomment-1806754266) applies to this bug?

It sounds like with a password set *and* a blank password you are getting an error in the `checking_password` step, which should only happen if the remote contents are encrypted with a different key (like a previous version of remotely-save).

**Comment by sboesen** [comment] 2023-11-12 09:33
Just to clarify - you experience this with a new **empty** S3 bucket? Can you provide other details so that I can try to reproduce this issue? I haven't been able to trigger this issue unless I am using the wrong password for encryption.

You are only using remotely-secure and not remotely-save anywhere, right? They are not compatible with each other.

**Comment by NewTypo** [comment] 2023-11-13 03:45
onedrive增量同步也出现问题
![image](https://github.com/sboesen/remotely-secure/assets/17538796/4ec7facb-a0d4-44b6-80ef-af074015f3ed)
![image](https://github.com/sboesen/remotely-secure/assets/17538796/1e6c65ab-43ec-4465-b0dc-9e72efa26ac8)

**Comment by sboesen** [comment] 2023-11-13 06:22
@NewTypo it looks like your sync folder has encrypted contents but you don't have a password set locally. What happens if you set the password locally?

**Comment by NewTypo** [comment] 2023-11-13 06:34
本地设置密码后可以同步，
![image](https://github.com/sboesen/remotely-secure/assets/17538796/5a43d00f-ae38-4e03-90d9-b11fd596bf12)
![image](https://github.com/sboesen/remotely-secure/assets/17538796/3d0822c6-08ff-4fca-bc7b-0fae98a6c45a)

**Comment by NewTypo** [comment] 2023-11-13 06:40
本地不设置加密密码
![image](https://github.com/sboesen/remotely-secure/assets/17538796/2f597989-6edd-430e-a6ac-978e8788ed95)
![image](https://github.com/sboesen/remotely-secure/assets/17538796/94b7bdee-4128-44f8-95bf-b3ddb2af511c)

**Comment by NewTypo** [comment] 2023-11-13 06:41
我不会编程，但如果有需要，希望可以帮助等到你 - ( ゜- ゜)つロ 乾杯~

**Comment by sboesen** [comment] 2023-11-13 06:54
Hey, so it worked! No issues after setting the password locally? Looks like it synced OK. Please let me know if it's still not working. Same goes for @Devinaille and @KuiyueRO.

**Comment by Devinaille** [comment] 2023-11-13 06:59
> Hey, so it worked! No issues after setting the password locally? Looks like it synced OK. Please let me know if it's still not working. Same goes for @Devinaille and @KuiyueRO.

Nop. Set the passwod after sync the unencrypted files is NOT work, it shows the error "error password ".
1. Delete all file on COS
2. Set the password
3. Manual sync the file -- that's ok 
4. Modified some file, then manual sync again -- that's ok

**Comment by sboesen** [comment] 2023-11-13 07:17
That's correct, it won't sync encrypted if you have previously synced unencrypted files. You have to always sync encrypted or always sync unencrypted. Unless I misunderstood?

Glad the encrypted sync with the password is working!

**Comment by Devinaille** [comment] 2023-11-13 07:55
You I misunderstood.


Without locally password, only the first manual sync can work. 
After that , it showed the password error message

**Comment by sboesen** [comment] 2023-11-13 09:25
Just to clarify this is what I think you are saying:

1. Create new vault
2. Do not set an encryption password
3. Add a file, manually sync (works)
4. Modify or add another file, manually sync (doesn't work)

Is this correct? From what you wrote earlier it sounds like syncing initially and subsequently does work but only if you set an encryption password, which is the main use case of this plugin.

> This is my step:
> 
> Delete all file on COS
> Set the password
> Manual sync the file -- that's ok
> Modified some file, then manual sync again -- that's ok

**Comment by 592146505** [comment] 2023-11-13 10:47
> Just to clarify this is what I think you are saying:
> 
> 1. Create new vault
> 2. Do not set an encryption password
> 3. Add a file, manually sync (works)
> 4. Modify or add another file, manually sync (doesn't work)
> 
> Is this correct? From what you wrote earlier it sounds like syncing initially and subsequently does work but only if you set an encryption password, which is the main use case of this plugin.
> 
> > This is my step:
> > Delete all file on COS
> > Set the password
> > Manual sync the file -- that's ok
> > Modified some file, then manual sync again -- that's ok

Indeed, I encountered a similar issue and upon examining the source code, I noticed a segment in sync.ts that might be related to this error:
```js
if (password === "") {
    return {
      ok: false,
      reason: "remote_encrypted_local_no_password",
    } as PasswordCheckType;
  }
```

**Comment by YIRU69** [comment] 2023-11-13 13:58
> Just to clarify this is what I think you are saying:
> 
> 1. Create new vault
> 2. Do not set an encryption password
> 3. Add a file, manually sync (works)
> 4. Modify or add another file, manually sync (doesn't work)

To show what I do

1. Create new vault and new S3
2. Set an password (password is ";")
3. manually sync (works)
4. manually sync agian (doesn't work), it show "checking password"

**Comment by sboesen** [comment] 2023-11-13 19:43
@592146505 @YIRU69 thank you. Not sure how I missed that `if password = ""` - I have published new release 0.4.6 which removes these plaintext checks. I don't think they are necessary anymore. Please let me know if you keep experiencing the issue with password checks.

To be honest I may disallow empty password in the future as that isn't secure, but I guess if someone chooses a weak password I'm not opposed ot that...

**Comment by YIRU69** [comment] 2023-11-14 00:22
@sboesen In the vision 0.4.6. The issue should not to happen. But If I manually sync, it like always sync all files. For example, I have 2853 files, I always syncs 2853 files and not to only sync the diff files.

**Comment by sboesen** [comment] 2023-11-14 01:00
I've noticed that as well, new release 0.4.7 attempts to fix this and worked locally for me. Let me know if you still have it uploading every file. 

Can you also confirm the sync issue (where it errors and does not sync) is resolved on your end? Thank you!

**Comment by YIRU69** [comment] 2023-11-14 01:36
Hi, I notice the console canceled. Maybe you can add it. Now I am testing it. Look fine.

**Comment by sboesen** [comment] 2023-11-14 01:53
> Hi, I notice the console canceled. Maybe you can add it.

Could you clarify what you mean? Please reopen the issue if there is still an issue here.

> Now I am testing it. Look fine.

Glad it seems to work! I opened a new issue #12 to track this request, I agree it would be useful. Closing this issue, please let me know if any issues remain.

**Comment by YIRU69** [comment] 2023-11-14 01:53
It look like worked! Fine! So I find the step 4 spend too much time. If you can speed up the step, it is a good news.
Sum advice
1. add console 
2. make the syncing progress display
3. as far as possible speed up the sync

**Closed** 2023-11-14 01:53 UTC
Labels: bug

**Comment by YIRU69** [comment] 2023-11-14 01:57
> Could you clarify what you mean? Please reopen the issue if there is still an issue here.

Compare to the older plugin (RS). The older plugin always output console. I think the console should output to let me know what happen.

**Comment by sboesen** [comment] 2023-11-14 02:01
for 1) the Obsidian team [requested we remove console logging](https://github.com/obsidianmd/obsidian-releases/pull/2523#issuecomment-1757915157) (probably for performance reasons?) during review, so I will not add these unless needed for debugging; I opened a new feature request #14 to track a new "debug" setting which outputs these, let me know if this makes sense to you.

for 2) we have #12 

for 3) I opened #13

**Comment by YIRU69** [comment] 2023-11-14 02:23
Yeah, particularly grateful to you! By the way, I test it on my phone. It worked well. Another I want to know that when I use the older SR  it always display delete the file (find the files number reduce), but the files number still can't change on the newer SR.

**Comment by sboesen** [comment] 2023-11-14 02:35
Happy to help! I think these features will make Remotely Secure better, appreciate the feedback.

> older SR 
What do you mean by older SR? 

> but the files number still can't change on the newer SR.
Which file numbers?

If this is a new separate issue please do open a [new bug report](https://github.com/sboesen/remotely-secure/issues/new?assignees=&labels=bug&projects=&template=bug_report.yml&title=%5BBug%5D%3A+) so we can track this better. Thank you!

**Comment by Devinaille** [comment] 2023-11-14 02:47
> Just to clarify this is what I think you are saying:
> 
> 1. Create new vault
> 2. Do not set an encryption password
> 3. Add a file, manually sync (works)
> 4. Modify or add another file, manually sync (doesn't work)
> 
> Is this correct? From what you wrote earlier it sounds like syncing initially and subsequently does work but only if you set an encryption password, which is the main use case of this plugin.
> 
> > This is my step:
> > Delete all file on COS
> > Set the password
> > Manual sync the file -- that's ok
> > Modified some file, then manual sync again -- that's ok

That's correct.

**Comment by YIRU69** [comment] 2023-11-14 03:13
> What do you mean by older SR?
The remotely save

> Which file numbers?
![Snipaste_2023-11-14_11-12-53](https://github.com/sboesen/remotely-secure/assets/48148292/3a8c9437-0b16-4643-88ac-30502a8c6e73)

> If this is a new separate issue
Just a little bit curiosity.
