### ISSUE TITLE
[Feature Request]: The ability to choose where to move deleted files (selecting the trash bin) after synchronization

### ISSUE THREAD

**Issue by MartinJDavis93** [sboesen/remotely-secure#34] opened 2023-11-23 18:28 UTC
### What feature are you suggesting?

Currently, the synchronization of deleted files is not very convenient. All deleted files on the computer are moved to the system trash, and this cannot be changed. Personally, I use the Obsidian trash in the Obsidian settings, which is much more convenient for me. It would be great if the extension took into account this selected parameter in Obsidian itself and synchronized the deletion content accordingly. If such implementation is challenging, then simply adding a corresponding parameter to the extension settings would suffice. This way, users could specify where to move files during synchronization if they have been deleted.

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by sboesen** [comment] 2023-11-23 22:14
Huh, didn't know this was a feature in Obsidian! Looks like it just puts the files in the .trash folder which shouldn't be difficult to replicate in remotely-secure. It's possible (no clue) this isn't something supported on mobile for some reason, but we could always selectively enable this feature.

I'll have to see if we can use the existing setting or have to add a new one, but this should definitely be doable and I like the feature request. One thing to consider may be the cost of keeping deleted files over a long period of time, but if it's configurable I don't see a reason to address this (yet).

Thanks for opening this issue!

**Comment by MartinJDavis93** [comment] 2023-11-24 13:15
> Huh, didn't know this was a feature in Obsidian! Looks like it just puts the files in the .trash folder which shouldn't be difficult to replicate in remotely-secure. It's possible (no clue) this isn't something supported on mobile for some reason, but we could always selectively enable this feature.
> 
> I'll have to see if we can use the existing setting or have to add a new one, but this should definitely be doable and I like the feature request. One thing to consider may be the cost of keeping deleted files over a long period of time, but if it's configurable I don't see a reason to address this (yet).
> 
> Thanks for opening this issue!

In mobile operating systems, there is no system-wide trash bin, unlike desktop operating systems where it relies on the standard file manager. I'm not sure where logically the files go after uninstalling the plugin. Perhaps because mobile OS lack a system-wide trash bin, the files are moved directly to Obsidian's trash. On the other hand, desktop OS have it, so there it goes into the system trash. No idea. The fact that this is inconvenient for those who rely on the app's trash, similar to other popular note-taking apps like Google Keep, OneNote, etc.

As for automatic clearing, it's not the plugin's task at all. It should be handled directly by the application itself, as it has implemented the app's trash. It's actually planned to be added in [the next version](https://obsidian.md/changelog/). So, you just need to implement the logic of where to move files after deletion: to the system trash, the app's trash, or permanently delete. It would be great if these settings synchronized with the app's settings, but it's not critical. If the plugin itself allows users to choose what to do with files after deletion, that would be fantastic.

I have another idea for a feature, but I'll open a separate request for that.

**Comment by sboesen** [comment] 2023-11-24 20:24
Implementation note - I'm not able to see where the setting can be read programmatically via an existing Obsidian API, but it looks like this setting is stored in the vault in `.obsidian/app.json` which should be easy to read/parse.

Might break in the event they change how they store this, but this works for me.

**Comment by MartinJDavis93** [comment] 2023-11-24 20:32
> Implementation note - I'm not able to see where the setting can be read programmatically via an existing Obsidian API, but it looks like this setting is stored in the vault in `.obsidian/app.json` which should be easy to read/parse.
> 
> Might break in the event they change how they store this, but this works for me.

In that case, it would probably be better to implement a separate option in the plugin settings. It'll be more stable, especially since it doesn't cause any inconvenience.

**Comment by MartinJDavis93** [comment] 2023-11-25 09:35
> Implementation note - I'm not able to see where the setting can be read programmatically via an existing Obsidian API, but it looks like this setting is stored in the vault in `.obsidian/app.json` which should be easy to read/parse.
> 
> Might break in the event they change how they store this, but this works for me.

I even found advantages in a separate option in the plugin settings related to [#40](https://github.com/sboesen/remotely-secure/issues/40). Of course, it will need practical testing, and it's at the user's own risk because data loss may occur if something goes wrong with synchronization (although I have never encountered such issues in all these years). In short, logically, if in the plugin settings, the option to permanently delete files is chosen instead of sending them to any trash bin, then after synchronization, when renaming a file, the previous file will be permanently deleted since the name is different, and in its place, the same file will appear but with a new name. Since this is a specific setting for the plugin, the user in Obsidian settings can choose to send deleted files to the Obsidian trash bin. So, if the user manually deletes a file, it goes to the trash bin, and if during synchronization the plugin sees that the file is missing (which includes simply renamed files), it will be permanently deleted. Without delving into details, the user may not even be aware that the file is duplicated and deleted. This, of course, does not solve the [#40](https://github.com/sboesen/remotely-secure/issues/40) problem, but it provides a pleasant variation of use to avoid cluttering the trash bin.

**Comment by MikeWi11s0n** [comment] 2023-11-28 20:19
+1

**Comment by MartinJDavis93** [comment] 2023-11-29 08:31
I would also sincerely appreciate it if you could implement this feature sooner. This is related to [#40](https://github.com/sboesen/remotely-secure/issues/40). Considering that we now have the excellent 'Sync on Save' feature and can shorten the time for auto-sync, it causes some discomfort when creating a new note. If you click to create a new note, by default, it will have the name Untitled. And since this change in files triggers 'Sync on Save' or auto-sync if its time has come, we end up with a synchronized file named Untitled on all devices where Obsidian is running at the time of creation. Since it's logical that you simply haven't had time to name the note yet, when you do give it a name, the Untitled note will be deleted, and during synchronization on the computer, it'll be sent to the system trash, consistently cluttering it. This happens frequently, practically with the creation of every new note. And your system trash is completely cluttered with files named Untitled, Untitled 1, 2, 3, etc. And if your note's name consists of several words, you can also get a note in the basket that has not yet been fully named.

Yes, this is relevant in cases where you have Obsidian running on multiple devices simultaneously, specifically either on computers or at least one of them being a computer, and the note is created on a phone (due to the absence of a system trash on mobile devices). But this is precisely my common scenario when I'm not near a computer, and I create a note using my phone while Obsidian is open on my computer. So, when I return, my trash is always cluttered with Untitled files. And yes, it'll still clutter the trash, albeit not the system one, but the Obsidian trash. However, this is much better for people who use the system trash on their computers, and clutter from Untitled files somewhat complicates their lives. And yes, this is relevant only for those people who either want to permanently delete files or send them to the Obsidian trash. For those who prefer the system trash will continue to face clutter issues with it.

**Comment by sboesen** [comment] 2023-12-01 03:55
<img width="534" alt="Screenshot 2023-11-30 at 7 54 20 PM" src="https://github.com/sboesen/remotely-secure/assets/248703/7c01e1c1-9345-4469-aba4-88c4ab8c46aa">

Fixed in 0.4.21 - Please reopen if this wasn't what you were thinking. Files deleted via Obsidian's UI are now moved to the .trash folder if configured.

**Closed** 2023-12-01 03:54 UTC
Labels: enhancement

**Comment by MartinJDavis93** [comment] 2023-12-01 13:13
> <img alt="Screenshot 2023-11-30 at 7 54 20 PM" width="534" src="https://private-user-images.githubusercontent.com/248703/287141603-7c01e1c1-9345-4469-aba4-88c4ab8c46aa.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE0MzY2NjQsIm5iZiI6MTcwMTQzNjM2NCwicGF0aCI6Ii8yNDg3MDMvMjg3MTQxNjAzLTdjMDFlMWMxLTkzNDUtNDQ2OS1hYmE0LTg4YzRhYjhjNDZhYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIwMVQxMzEyNDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jN2MzNGU1Mzk3MGE0ODczODU0ODExMDRmZDNjMWYxZGNiYmZhODJkNzljMGRmMWFmMmMzNTEwOTU0YTRhZDAwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.42KUFOBN1JePRK2dYQE467MFL1MdiYMXD7hcs4_IaA4">
> Fixed in 0.4.21 - Please reopen if this wasn't what you were thinking. Files deleted via Obsidian's UI are now moved to the .trash folder if configured.

I'm sincerely grateful! This is exactly what was needed. I also decided to complement #37, taking into account this implementation.

**Comment by lyiton** [comment] 2023-12-05 03:13
> <img alt="Screenshot 2023-11-30 at 7 54 20 PM" width="534" src="https://private-user-images.githubusercontent.com/248703/287141603-7c01e1c1-9345-4469-aba4-88c4ab8c46aa.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE3NDU5NDIsIm5iZiI6MTcwMTc0NTY0MiwicGF0aCI6Ii8yNDg3MDMvMjg3MTQxNjAzLTdjMDFlMWMxLTkzNDUtNDQ2OS1hYmE0LTg4YzRhYjhjNDZhYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIwNVQwMzA3MjJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00YWZkMzQxMzEzOTc3MzgxMWUzNjk4MWQ1ZGJlYmQ5MDgxZjNkNDgyMmY1ZTFiMDc3ZWI1NDQ3NjYwZTYwZTliJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.vd6FNiBjWRMd052uXuzGM-uqOsKL27mVHpGT9M1sBS0">
> 已在 0.4.21 中修复 - 如果这不是您的想法，请重新打开。通过 Obsidian 的 UI 删除的文件现在（如果已配置）将移动到 .trash 文件夹。

I have settings in Obsidian's Files & Links to move deleted files to System Trash, so this feature doesn't work for me, it still moves to System Trash. Is this feature a conflict with Obsidian's own settings?

**Comment by sboesen** [comment] 2023-12-05 06:40
@lyiton If you want files moved to the system trash, keep this turned off. 

> so turning this feature on doesn't work for me, it still moves to System Trash

Do you want Remotely Sync to move files to the .trash folder? If so turn it on. It will work even if you specify system trash in Obsidian's settings - they are separate settings (as much as I would like it to be only one setting it doesn't seem possible to read Obsidian's core settings easily from a plugin).

**Comment by lyiton** [comment] 2023-12-05 07:00
> It will work even if you specify system trash in Obsidian's settings - they are separate settings

I specified system trash in Obsidian's settings, and the plugin's settings are turned on, but it still prompts me whether to put it in system trash?
![Snipaste_2023-12-05_14-48-28](https://github.com/sboesen/remotely-sync/assets/76651858/84e32b58-2df2-4b08-b885-814e72637179)
![Snipaste_2023-12-05_14-48-45](https://github.com/sboesen/remotely-sync/assets/76651858/e374f6ee-53b8-4efb-925a-2a8f7cb980d5)

**Comment by sboesen** [comment] 2023-12-05 07:43
I should clarify - the plugin setting only determined if files deleted by Remotely Sync (like during a sync) are moved to the .trash folder. Deleting a file via Obsidian's UI still uses your Obsidian setting for .trash/system trash. Let me know if it's still not clear. I think it would be simpler to use .trash for both or system trash for both, but the screenshot you shared makes sense to me and is intended behavior.

Here is the code change if it helps: https://github.com/sboesen/remotely-sync/commit/68f07518fdd7ad5b36add23f3f5dff2dcb5f3a00#diff-4fab5baaca5c14d2de62d8d2fceef376ddddcc8e9509d86cfa5643f51b89ce3dL936-R945

**Comment by sboesen** [comment] 2023-12-05 07:49
Updated the description for the setting (in english only) to clarify better: https://github.com/sboesen/langs/commit/31e940e7eb4da5c8f07c37ce5bcd6fc7b10ccced

**Comment by lyiton** [comment] 2023-12-05 08:05
Aha, I know, I misunderstood. The description should really be revised to remove ambiguity. Thank you!
